baseURL: "https://muhammedbulutay.com/" 
title: Muhammed Bulutay
theme: PaperMod

enableInlineShortcodes: true
enableRobotsTXT: true
pagination:
  pagerSize: 20

taxonomies:
    tag: tags

disableKinds:
  - rss

menu:
    main:
        - name: Research
          url: research/
          weight: 2
        - name: Teaching
          url: teaching/
          weight: 3

params:
    description: "This website hosts Muhammed Bulutay's research and course information."
    author: Muhammed Bulutay
    # googleAnalyticsID: "G-XXXXX"
    DateFormat: "January 2006"
    defaultTheme: light
    hideFooter: false
    disableThemeToggle: true
    ShowShareButtons: false
    ShowReadingTime: false
    disableSpecial1stPost: true
    disableAnchoredHeadings: true
    ShowPostNavLinks: false
    ShowBreadCrumbs: false
    ShowCodeCopyButtons: true
    ShowAllPagesInArchive: false
    MainSections: ["research","teaching"]
    ShowToc: false
    disableScrollToTop: true
    TocOpen: true
    ShowWordCount: false
    UseHugoToc: true
    comments: false
    math: true
    profileMode:
      enabled: true
      title: Dr. Muhammed Bulutay
      subtitle: >-
        I am a postdoctoral researcher in economics at 
        <a href="https://www.awi.uni-heidelberg.de/en/people/faculty/dr-muhammed-bulutay" style="color:#0000FF !important; text-decoration-color:#0000FF !important;">Heidelberg University</a>.
        I do research on the micro-foundations of macro-economic activity, with an emphasis on causality.
        I have worked on topics such as expectations and strategic uncertainty.

        <br><br><strong>News</strong>
        <br><small>Presentation: “Overprecision and (Ir)rational Inattention” at FUR 2026, Alicante, 10–12 June.</small>
      imageUrl: "picture.jpg"
      imageWidth: 190
      imageHeight: 190
      buttons:
        - name: Research
          url: research/
        - name: Teaching
          url: teaching/
    socialIcons:
        - name: CV
          url: https://drive.google.com/file/d/1ZP6-lDDKrj4kiodIxh2BlZGafvTzB_gW/view?usp=sharing
        - name: Email
          url: mailto:muhammed.bulutay@awi.uni-heidelberg.de
        - name: Google Scholar
          url: https://scholar.google.com/citations?user=UVNay1sAAAAJ&hl=en
        - name: X
          url: https://x.com/mvbulutay
        - name: LinkedIn
          url: https://www.linkedin.com/in/muhammed-bulutay
        - name: Bluesky
          url: https://bsky.app/profile/mvbulutay.bsky.social

    assets:
        disableScrollBarStyle: true
    cover:
        hiddenInList: true
        hiddenInSingle: true
    label:
      text: "Muhammed Bulutay"
      icon: favicon.ico
      iconHeight: 18

markup:
    goldmark:
        renderer:
            unsafe: true
    highlight:
        guessSyntax: true
        style: autumn 
    tableOfContents:
        endLevel: 2
        ordered: false
        startLevel: 2